dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.111
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.111
- name: nodey120
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: nodey126
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
